---
apiVersion: v1
kind: Pod
matadata:
  name: ghost-pod
  namespace: test-ns
  labels:
    type: CMS
    author: intelliqit
spec:
  containers:
    - name: ghost
      image: ghost
      env:
        - name: NODE_ENV
          value: development
      ports:
        - containerPort: 2368
          hostPort: 8080
...
