apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    type: webserver
spec:
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 8080
      resources:
        requests:
          memory: "24Mi"
          cpu: "100m"
        limits:
          memory: "64Mi"
          cpu: "200m"
...
