---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    type: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: httpd-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
          resources:
            requests:
              memory: "24Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
...
