---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    author: sneha
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    author: intelliqit
    app: proxy
...
